-- use DataInitRunner class instead
-- INSERT INTO role (description, name)
-- VALUES ('System admin', 'ADMIN');
-- INSERT INTO role (description, name)
-- VALUES ('Event Organiser', 'EVNTORG');
-- INSERT INTO role (description, name)
-- VALUES ('Business Partner ', 'BIZPTNR');
-- INSERT INTO role (description, name)
-- VALUES ('Attendee', 'ATND');